### ISSUE TITLE
currently assigning admins in the /api/class POST route will not update users is_admin field

### ISSUE THREAD

**Issue by asipser** [mit6148-staff/submission-portal#4]
current mechanism totally ignores those users which is wrong. The /api/class/class_id/add-admin route relies upon the fact that the user has registered under the new active-year. This route is different as those users do not exist yet. Maybe the solution for this lies in user registration. I see two options:

1) Check on user registration if any previous user documents exist for that github username, and if there are check if any of them has admin status (and if they do set the new user to have admin status by default). If we did this then we would not need to specify admins when creating a new class. This assumes some admins will carry over year to year.

2. Upon user registration check to see if the admins for the current_year has that user's github username in the list of admin github usernames. If so, give them admin privs. This is probably the cleaner solution?

Opinions @cory2067 ?

**Comment by asipser** [comment]
I implemented both solutions but wasn't too happy with how #1 looked, so I commented it out. @cory2067 can look at passport.js and decide whether it's worth keeping.

**Comment by cory2067** [comment]
solution 2 is good
